"""build_phrase_overrides.py — mine phrases from any text corpus.

Walks a directory of .md / .txt files, extracts 2-4 character phrases
that appear ≥ THRESHOLD times, computes their Bopomofo via pypinyin,
and rewrites ``../thesis_phrase_overrides.py`` with the mined list.

Use this to teach bopo-fix the vocabulary specific to your writing —
the more text you have, the better the override file gets.

Usage:
    python tests/build_phrase_overrides.py --corpus ~/Documents/my-papers
    python tests/build_phrase_overrides.py --corpus . --min-count 50
    python tests/build_phrase_overrides.py --corpus /data --max-phrases 1000
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import Counter
from pathlib import Path

_HERE = Path(__file__).resolve().parent.parent
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))

from chewing_wrapper import _bopomofo_of_phrase

CJK_RE = re.compile(r"[一-鿿]+")
DEFAULT_OUTFILE = _HERE / "thesis_phrase_overrides.py"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--corpus", required=True,
                    help="Directory to scan for .md/.txt files.")
    ap.add_argument("--min-count", type=int, default=30,
                    help="Phrases must appear at least this many times "
                         "to be included (default: 30).")
    ap.add_argument("--max-phrases", type=int, default=500,
                    help="Top N phrases by frequency to keep (default: 500).")
    ap.add_argument("--max-files", type=int, default=200,
                    help="Stop after scanning this many files (default: 200).")
    ap.add_argument("--out", default=str(DEFAULT_OUTFILE),
                    help=f"Output file path (default: {DEFAULT_OUTFILE}).")
    args = ap.parse_args()

    root = Path(args.corpus).expanduser().resolve()
    if not root.exists():
        print(f"❌ corpus root not found: {root}", file=sys.stderr)
        return 2

    phrase_count: Counter[str] = Counter()
    files = 0
    for p in root.rglob("*"):
        if files >= args.max_files:
            break
        if not p.is_file() or p.suffix.lower() not in {".md", ".txt"}:
            continue
        try:
            sz = p.stat().st_size
        except OSError:
            continue
        if sz < 5_000 or sz > 1_000_000:
            continue
        try:
            text = p.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        files += 1
        for chunk in CJK_RE.findall(text):
            for size in (2, 3, 4):
                for i in range(len(chunk) - size + 1):
                    phrase_count[chunk[i:i + size]] += 1

    common = [(p, c) for p, c in phrase_count.most_common(args.max_phrases * 4)
              if c >= args.min_count][:args.max_phrases]

    print(f"# scanned {files} files, kept {len(common)} phrases "
          f"(≥ {args.min_count} occurrences)", file=sys.stderr)

    out_path = Path(args.out)
    lines = [
        '"""thesis_phrase_overrides.py — auto-generated phrase preferences.',
        "",
        f"Generated by tests/build_phrase_overrides.py from corpus:",
        f"    {root}",
        f"({files} files scanned, top {len(common)} phrases ≥ {args.min_count} "
        f"occurrences)",
        "",
        "Re-generate with the same command, or hand-edit to add/remove entries.",
        '"""',
        "from __future__ import annotations",
        "",
        "THESIS_PHRASES: dict[str, str] = {",
    ]
    for phrase, count in common:
        bopo = _bopomofo_of_phrase(phrase)
        if bopo:
            lines.append(f"    {bopo!r}: {phrase!r},  # {count}")
    lines.append("}")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"✅ wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
