"""build_char_overrides.py — mine single-char preferences from a corpus.

For each Bopomofo, finds the character most frequently used IN YOUR
CORPUS. Useful when your domain prefers a specific character among
homophones (e.g., 徵 over 爭 for ㄓㄥ in research papers).

Usage:
    python tests/build_char_overrides.py --corpus ~/Documents/my-papers
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

_HERE = Path(__file__).resolve().parent.parent
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))

from pypinyin import Style, pinyin

CJK_RE = re.compile(r"[一-鿿]+")
DEFAULT_OUTFILE = _HERE / "thesis_corpus_overrides.py"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--corpus", required=True)
    ap.add_argument("--min-count", type=int, default=30)
    ap.add_argument("--max-files", type=int, default=200)
    ap.add_argument("--out", default=str(DEFAULT_OUTFILE))
    args = ap.parse_args()

    root = Path(args.corpus).expanduser().resolve()
    if not root.exists():
        print(f"❌ corpus root not found: {root}", file=sys.stderr)
        return 2

    char_count: dict[str, int] = defaultdict(int)
    files = 0
    for p in root.rglob("*"):
        if files >= args.max_files:
            break
        if not p.is_file() or p.suffix.lower() not in {".md", ".txt"}:
            continue
        try:
            sz = p.stat().st_size
        except OSError:
            continue
        if sz < 5_000 or sz > 5_000_000:
            continue
        try:
            text = p.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        files += 1
        for chunk in CJK_RE.findall(text):
            for ch in chunk:
                char_count[ch] += 1

    print(f"# scanned {files} files, {len(char_count)} unique chars "
          f"({sum(char_count.values()):,} total CJK)", file=sys.stderr)

    bopo_to_best: dict[str, tuple[str, int]] = {}
    for ch, cnt in char_count.items():
        try:
            result = pinyin(ch, style=Style.BOPOMOFO, errors="ignore")
        except Exception:
            continue
        if not result or not result[0] or not result[0][0]:
            continue
        bp = result[0][0]
        prev = bopo_to_best.get(bp)
        if prev is None or cnt > prev[1]:
            bopo_to_best[bp] = (ch, cnt)

    overrides = {bp: ch for bp, (ch, cnt) in bopo_to_best.items()
                 if cnt >= args.min_count}

    out_path = Path(args.out)
    lines = [
        '"""thesis_corpus_overrides.py — auto-generated single-char overrides.',
        "",
        f"Generated by tests/build_char_overrides.py from corpus:",
        f"    {root}",
        f"({files} files scanned, {len(overrides)} chars ≥ "
        f"{args.min_count} occurrences)",
        '"""',
        "from __future__ import annotations",
        "",
        "THESIS_CORPUS_OVERRIDES: dict[str, str] = {",
    ]
    for bp in sorted(overrides):
        lines.append(f"    {bp!r}: {overrides[bp]!r},")
    lines.append("}")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"✅ wrote {out_path} ({len(overrides)} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
